"""add todo model

Revision ID: 9e2fed1a848d
Revises: 72a8d94083ed
Create Date: 2023-11-16 17:00:06.544332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2fed1a848d'
down_revision: Union[str, None] = '72a8d94083ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('todo', sa.Column('length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'length')
    op.drop_column('todo', 'duration')
    # ### end Alembic commands ###
